version: 0.2
 
phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - node -v
      - npm -v
      - cd demo && npm install
 
  build:
    commands:
      - cd demo && npm run build
 
artifacts:
  files:
    - "**/*"
  base-directory: demo/dist